# Generated by Django 5.2.1 on 2025-05-23 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendinginstitution',
            name='revoked',
            field=models.BooleanField(default=False),
        ),
    ]
