# Generated by Django 5.2.1 on 2025-05-23 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0002_pendinginstitution_revoked'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('student_regNumber', models.CharField(max_length=20)),
                ('student_surname', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=200)),
                ('degree_class', models.CharField(max_length=100)),
                ('date_issued', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
